### ISSUE TITLE
sending packets to ff02::1 not possible on FreeBSD

### ISSUE THREAD

**Issue by koeppea** [sam-github/libnet#56]
Hi,

while sending packets using libnet to the multicast address **ff02::1** on Linux works,
it doesn't work on FreeBSD.

It fails with:
```
libnet_write: libnet_write_raw_ipv6(): -1 bytes written (Network is unreachable)
```
However, the route **ff00::/8** is really not present on FreeBSD while it is on Linux.
But I woder why `ping6 -I em0 ff02::1` works on FreeBSD though?

Is there any chance to specify the outgoing interface in *libnet_t*?

**Comment by sam-github** [comment]
`libnet_init()` has a `device` argument to specify the interface. That's not working?

**Comment by koeppea** [comment]
Hi sam,

I am proceeding to the issue step by step.
Meanwhile I've been able to get the issue worked out.
First of all, specifying the interface name to `libnet_init()` didn't help.
I've been able to solve it by specifying the **IPV6_MULTICAST_IF** socket option to `l->fd`.

The Multicast packet goes on the wire with the correct MAC address and even the IPv6 address.
However, there seem to be an issue in building the IPv6 header. 
It seems that it exists 2 times.
I'll open a new issue on that.

Closing this one.

**Comment by sam-github** [comment]
> I've been able to solve it by specifying the IPV6_MULTICAST_IF socket option to l->fd.

How did you do this, can you show code?

Can/should this be done by libnet?

**Comment by koeppea** [comment]
Sure, here it is:
```c
   unsigned int idx;
   idx = if_nametoindex("em0");
   if (idx == 0) {
       perror("Interface index not found");
       exit(2);
   }

   if (setsockopt(l6->fd, IPPROTO_IPV6, IPV6_MULTICAST_IF, &idx, sizeof(idx)))
       perror("Unable to set socket option");
```
However to achieve this you will need the interface name. If you have you can set this option. My observations have shown not negative impact even the socket is not being used for multicast traffic.
If you don't have the interface name, you can't set this option AFAICS.

However the above example concentrates on IPv6. But the same applies for IPv4 with **IPPROTO_IP** and **IP_MULTICAST_IF**.

Don't know if it's a good idea setting it within **libnet**.

**Comment by sam-github** [comment]
Setting every time would be bad, but having some kind of API to set it, that worked on ip4 or ip6 would be good. If you care to PR such an API it would be nice to have.

**Comment by koeppea** [comment]
I can do one up.

**Comment by koeppea** [comment]
Just a short summary of what we found out in issue #57:
 1. On FreeBSD it's not possible at all even with the socket option: sending crap.
 2. On Linux it's possible: The kernel somehow merges all information together and sending out the packet as expected.

Based on the findings in #57, do you think it's still necessary to create this API thing?

**Comment by sam-github** [comment]
No, looks like it works ok.
