### ISSUE TITLE
IPv6 packet build incorrectly on FreeBSD

### ISSUE THREAD

**Issue by koeppea** [sam-github/libnet#57]
Hi,

while porting a ettercap to FreeBSD I'm now concentrating on the IPv6 support on FreeBSD.
However I'm experiencing a strange issue when the IPv6 packet is being build with libnet.
It seems that is somewhat incorrectly created and even IPv6 header appears twice:
```
60 00 00 00 00 30 ff 01  fe 80 00 00 00 00 00 00 
                         ^------------------------- source
0a 00 27 ff fe bb c6 7f  ff 02 00 00 00 00 00 00 
                         ^------------------------- destination
00 00 00 00 00 00 00 01  60 00 00 00 00 08 3a ff 
                         ^------------------------- 2nd IPv6 header
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 
^-------------------------------------------------- real source (yes stupidly set to ::)
ff 02 00 00 00 00 00 00  00 00 00 00 00 00 00 01 
^-------------------------------------------------- real destination
80 00 d0 ba af fe 00 00
^-------------------------------------------------- real IPv6 payload (ICMP6_ECHO_REQUEST)
```

This is the relevant libnet code:
```c
   t = libnet_build_icmpv6_echo(ICMP6_ECHO_REQUEST, /* type */
                                0,                  /* code */
                                0,                  /* checksum */
                                0xaffe,             /* id */
                                0,                  /* sequence number */
                                NULL,               /* data */
                                0,                  /* data size */
                                l6,                 /* handle */
                                0);                 /* ptag */
   if (t == -1) {
      fprintf(stderr, "Error building ICMPv6 layer: %s\n",
            libnet_geterror(l6));
      exit(5);
   }
   libnet_toggle_checksum(l6, t, LIBNET_ON);

   t = libnet_build_ipv6(0,                        /* traffic class */
                         0,                        /* flow label */
                         LIBNET_ICMPV6_H,          /* payload length */
                         IPPROTO_ICMPV6,           /* next header */
                         255,                      /* hop limit */
                         src,                      /* source address */
                         dst,                      /* destination address */
                         NULL,                     /* payload */
                         0,                        /* payload size */
                         l6,                       /* handle */
                         0);                       /* ptag */
   if (t == -1) {
      fprintf(stderr, "Error building IPv6 layer: %s\n",
            libnet_geterror(l6));
      exit(6);
   }

```

The same code builds the packet as expected on Linux. It seems that the issue is limited to (Free)BSD systems.

**Comment by sam-github** [comment]
Seems like a bug, but just to let you know, I don't have the time to track it down.

**Comment by koeppea** [comment]
Yes, I'm already in process of tracking it down.

**Comment by koeppea** [comment]
It becomse somewhat more clear now.
When the socket is being created in *libnet_open_raw6()* (`l->fd = socket(AF_INET6, SOCK_RAW, IPPROTO_RAW);`) the procotol (*IPPROTO_RAW = 255*) is used as the next header field in the first IPv6 header.
When the packet is being sent in *libnet_write_raw_ipv6()* (`c = sendto(l->fd, packet, size, 0, (struct sockaddr *)&sin, sizeof(sin));`) the *size* is used as the payload length field and the address of *sin* for the destination address in the first IPv6 header.
Then the content of packet is being appended.

This is what explains the above result.
I've found the [following mailing list entry](http://lists.freebsd.org/pipermail/freebsd-pf/2006-May/002174.html) which explains this. 
However, this means that handling IPv6 on BSD systems becomes somewhat painful. I'm not very used to the BPF framework.

**Comment by sam-github** [comment]
Hm, why not use a link-level socket, so you can write fully constructed packets, and evade what the OS does or does not allow you to control about the IPv6 headers?

It looks like they are supported for BPF:

https://github.com/sam-github/libnet/blob/master/libnet/src/libnet_link_bpf.c#L94

But I'm not sure what implementation FreeBSD uses.

**Comment by koeppea** [comment]
OK now I know what I've to do.
using the bpf link-layer framework of libnet works as expected. However now I have to take care of building the link-layer addresses including the special multicast LLAs.

But I think that's OK.

So closing this one.

**Comment by koeppea** [comment]
Thanks by the way for your support.

**Comment by koeppea** [comment]
I've digged a bit deeper meanwhile.
This is for anybody of intrest as it's not a solution to this but a explanation.
On Linux you find in **man 7 raw**:
```
       A  protocol  of IPPROTO_RAW implies enabled IP_HDRINCL and is able to send any IP protocol
       that is specified in the passed header.  Receiving of all IP protocols via IPPROTO_RAW  is
       not possible using raw sockets.
...
       If  IP_HDRINCL  is specified and the IP header has a nonzero destination address, then the
       destination address of the socket is used to route  the  packet.   When  MSG_DONTROUTE  is
       specified,  the destination address should refer to a local interface, otherwise a routing
       table lookup is done anyway but gatewayed routes are ignored.
```
Which means, in Linux, a Raw socket by default has this option enabled.
What the option does is actually described in **man 7 ip**:
```
       IP_HDRINCL (since Linux 2.0)
              If  enabled,  the user supplies an IP header in front of the user data.  Only valid
              for SOCK_RAW sockets.  See raw(7) for more information.  When this flag is  enabled
              the values set by IP_OPTIONS, IP_TTL and IP_TOS are ignored.
```

However in **man 7 ipv6** I've not found a dedicated entry in the documentation but a view into the kernel source revealed that for Raw sockets of the AF INET6 behaves as AF INET and sets the socket option IP_HDRINCL (or in terms of IPv6: functionality) by default and provides a kernel function () which takes care of this scenario.

If I set for example this socket option to 0 for the IPv4 address family, I get exaxtly the same issue for IPv4 which I experience for IPv6 on BSD based systems at the moment.

However within the FreeBSD documentation and within the libnet documentation I find some statements in regard to that:
libnet/CHANGELOG:
```
Fixed IPv6 support (to some extent) removed the IP_HDRINCL stuff and
reworked the resolver stuff to use net_pton() and inet_ntop().
[...]
0.1 01.05.1998 Initial release, contains:
network byte order -> human readable IP address,
human readable IP address -> network byte order,
simple raw socket / IP_HDRINCL wrapper,
TCP checksum (x86 assembly implementation)
```

and in the libnet/TODO:
```
 - Fix IPv6. According to RFC 2992:
"Another difference from IPv4 raw sockets is that complete packets
(that is, IPv6 packets with extension headers) cannot be read or
written using the IPv6 raw sockets API. Instead, ancillary data
objects are used to transfer the extension headers, as described
later in this document. Should an application need access to the
complete IPv6 packet, some other technique, such as the datalink
interfaces BPF or DLPI, must be used.
All fields in the IPv6 header that an application might want to
change (i.e., everything other than the version number) can be
modified using ancillary data and/or socket options by the
application for output. All fields in a received IPv6 header (other
than the version number and Next Header fields) and all extension
headers are also made available to the application as ancillary data
on input. Hence there is no need for a socket option similar to the
IPv4 IP_HDRINCL socket option."
```
This means that this is a known issue. However only limited to BSD based systems.

For Linux there is a dedicated Kernel function which takes care forwarding if this options is set regardless of which family. In contrast, BSD based systems did it for IPv4 but not for IPv6 due to referencing to BPF where you have to reimplement all the shit from scratch,
```

It seems really to remain to tread packets differently as if sent by a Linux Kernel or a BSD based Kernel. *BSD based systems just don't bother this option for AF_INET6 based raw sockets by referencing to BPF API. However this lets the user alone with all the stuff like link-layer resolution and IP routing thath might bring up worse results if each and every implementation is done by the users on their own.

I'll try to reach out to the FreeBSD guys but I don't really see much chance for success.
