### ISSUE TITLE
OS X: build error

### ISSUE THREAD

**Issue by alex-v1981** [sam-github/libnet#59]
Tried to build the source code in the OS X.

$ ./autogen.sh
$ ./configure
$ make

Error:

make[3]: *** No rule to make target `libnet*.3', needed by `all-am'.  Stop.

**Comment by sam-github** [comment]
The generated man pages aren't committed into git, you have to build them. See https://github.com/sam-github/libnet/blob/master/BUILD-FROM-GIT.txt
