### ISSUE TITLE
undef icmp_type breaks other code

### ISSUE THREAD

**Issue by foxx** [sam-github/libnet#63]
See following [line](https://github.com/sam-github/libnet/blob/bda42883b37b28aab0a5a89d377fc0db1c41b9da/libnet/include/libnet/libnet-headers.h#L1098).

>        /* TODO this hack conflicts with the system headers, which is why we
>         * undef what they do, and it also damages dnet/dumbnet's headers if
>         * they are included after ours. Fixing will break API, though, so
>         * we leave it for now.
>         */

Is this likely to be fixed?

**Comment by sam-github** [comment]
What fix would you propose?

**Comment by foxx** [comment]
I'm not sure, any change would almost certainly be backwards incompatible. Are you open to breaking changes?

**Comment by sam-github** [comment]
Not for cosmetic fixes. As long as you include your headers in the right order this works OK. Breaking every user of libnet's ICMP code would be a hard sell.

Unless you have some decent suggestions, and/or, a serious problem. For example, it would be possible to protect the macros with further protection, so apps could opt-out of the conflicting definitions if they wanted.

**Comment by foxx** [comment]
I'm going to close this out for now, as I haven't got any concrete suggestions of the best way to fix this. But at least this is here for future discussion if others run into similar issues.
