### ISSUE TITLE
  Hello, is this libnet support GTPV1 agreement?

### ISSUE THREAD

**Issue by wtyvvv** [sam-github/libnet#64]
Hello, is this libnet support GTPV1 agreement?

thanks so much

**Comment by sam-github** [comment]
No, I don't know what gtpv is

**Comment by wtyvvv** [comment]
hi sam，thanks you reply, GPRS Tunneling Protocol (GTP) ，GTP version 1,thanks

**Comment by sam-github** [comment]
oh, I don't know all the protocols it supports, read the headers, maybe its there.

**Comment by wtyvvv** [comment]
thanks so much,now i already know how to write gtp herder struct,but i found one problem,in the libnet lib, 
Can I send IPv4 packets many times? This like

A complete packet of mobile network has these layers,

Ethernet-->Internet Protocol Version 4 -->User Datagram Protocol --> GPRS Tuneling Protocol-->Internet Protocol Version 4-->Transmission / Control Protocol

So there are two layers of IP layer protocol, what do I need to pay attention to when I construct the IPv4 layer? I now send packets to the Tuneling Protocol GPRS on a layer of IPV4 is not, and can not be identified

ibnet_init(
            LIBNET_LINK,							/* injection type */
            device,                                 /* network interface */
            errbuf); 
t = libnet_build_tcp
t = libnet_build_ipv4
t = libnet_build_gtpv1
t = libnet_build_udp
t = libnet_build_ipv4
t = libnet_build_gtpv1

here i call libnet_build_ipv4 two times,thanks

**Comment by sam-github** [comment]
I suggest you try, and see how it goes.

**Comment by wtyvvv** [comment]
thanks,it's successed already.
but i find one problem, libnet  can not close the socket,i'm use libnet-1.2-rc3 ,
this is my code, my laptop set ulimit -n is 2048

#include <libnet.h>
int
main(int argc, char *argv[])
{
	    char errbuf[LIBNET_ERRBUF_SIZE];

    libnet_t *l;
    libnet_ptag_t t;
	while(1){


			l = libnet_init(
					LIBNET_LINK,                            /* injection type */
					NULL,                                   /* network interface */
					errbuf);                                /* errbuf */

			if (l == NULL)
			{
				fprintf(stderr, "libnet_init() failed: %s\n", errbuf);
				exit(EXIT_FAILURE);
			}
				libnet_destroy(l);


	}
}
[root@localhost]# ./t
libnet_init() failed: libnet_ifaddrlist(): fopen(proc_dev_file) failed: Too many open files

i found here have many not closed socket,thanks

[root@localhost]# ls -lh /proc/2069/fd
total 0
lrwx------ 1 root root 64 Nov 24 21:52 0 -> /dev/pts/3
lrwx------ 1 root root 64 Nov 24 21:52 1 -> /dev/pts/3
lrwx------ 1 root root 64 Nov 24 21:52 10 -> socket:[313674]
lrwx------ 1 root root 64 Nov 24 21:52 11 -> socket:[313676]
lrwx------ 1 root root 64 Nov 24 21:52 12 -> socket:[313678]
lrwx------ 1 root root 64 Nov 24 21:52 13 -> socket:[313680]
lrwx------ 1 root root 64 Nov 24 21:52 14 -> socket:[313682]
lrwx------ 1 root root 64 Nov 24 21:52 15 -> socket:[313684]
lrwx------ 1 root root 64 Nov 24 21:52 16 -> socket:[313686]
lrwx------ 1 root root 64 Nov 24 21:52 17 -> socket:[313688]
lrwx------ 1 root root 64 Nov 24 21:52 18 -> socket:[313690]
lrwx------ 1 root root 64 Nov 24 21:52 19 -> socket:[313692]


please ask ,What should I do to correct the problem?  thanks so much.

**Comment by sam-github** [comment]
you should report above as a seperate bug

I don't have time to fix, but I will review a PR if you fix it

also, what you are doing is weird. Call init once, and use it  over and over, you are creating a new raw  socket for every packet you send

**Comment by wtyvvv** [comment]
ok,thanks so much, doing this so weird,i just test , thanks
