### ISSUE TITLE
endianess problem about libnet src 

### ISSUE THREAD

**Issue by iceonsun** [sam-github/libnet#68]
platform: Mac OS 11.6
libnet version: 1.1.6.

I'm confused about endianess of src and dst in libnet.
In libnet-functions.h, I see:
`/**
 * Builds a version 4 RFC 791 Internet Protocol (IP) header.
 *
 * @param ip_len total length of the IP packet including all subsequent data (subsequent
 *   data includes any IP options and IP options padding)
 * @param tos type of service bits
 * @param id IP identification number
 * @param frag fragmentation bits and offset
 * @param ttl time to live in the network
 * @param prot upper layer protocol
 * @param sum checksum (0 for libnet to autofill)
 * @param src source IPv4 address (little endian)
 * @param dst destination IPv4 address (little endian)
 * @param payload optional payload or NULL
 * @param payload_s payload length or 0
 * @param l pointer to a libnet context
 * @param ptag protocol tag to modify an existing header, 0 to build a new one
 * @return protocol tag value on success, -1 on error
 */`
It says src and dst are little endian.

But when see examples in github, they all use big endian. like this:

https://github.com/sam-github/libnet/blob/bda42883b37b28aab0a5a89d377fc0db1c41b9da/libnet/sample/bgp4_hdr.c#L103
https://github.com/sam-github/libnet/blob/bda42883b37b28aab0a5a89d377fc0db1c41b9da/libnet/sample/bgp4_hdr.c#L172
Following code is for above link:
`t = libnet_build_ipv4(
        length,                                     /* length */
        0,                                          /* TOS */
        242,                                        /* IP ID */
        0,                                          /* IP Frag */
        64,                                         /* TTL */
        IPPROTO_TCP,                                /* protocol */
        0,                                          /* checksum */
        src_ip,                                     /* source IP */
        dst_ip,                                     /* destination IP */
        NULL,                                       /* payload */
        0,                                          /* payload size */
        l,                                          /* libnet handle */
        0);     `
Big endian of src and dst works on my machine.
So I am wondering which endianess on earch do libnet use.

**Comment by sam-github** [comment]
Args encoded into a width less than one byte don't have an endianness, which is most of that function's params. 

I've no time to read the source, but in the examples you link, name2addr is used so the output would be in network byte order (little endian). If in doubt, read the source, its pretty easy to read for this kind of stuff.
