### ISSUE TITLE
Missing neighbor argument in libnet_build_ospfv2_hello()

### ISSUE THREAD

**Issue by troglobit** [sam-github/libnet#69]
Hi,

I recently picked up maintenance of Nemesis and finished the port to libnet1 (started in 2005). I noticed that the `libnet_build_ospfv2_hello()` function no longer has a neighbor argument, yet the `struct libnet_ospf_hello_hdr` still has a `hello_nbr` field.

As a result, there is no way to set the Active Neighbor address field in the packet.

I could prepare a pull-request, but I'm not sure how you'd like this fixed:
1. Re-add the `neighbor` argument to `libnet_build_ospfv2_hello()`
2. Remove the `hello_nbr` field from the struct and let people use payload instead
3. Add a new API, e.g. `libnet_build_ospfv2_hello2()` or `libnet_build_ospfv2_hello_neighbor()` that has the neighbor filed. I.e. like 1., but with a non ABI-breaking new API.

**Comment by sam-github** [comment]
Please don't break the ABI/API. No strong feelings about 2 vs 3, what do you think is best?

**Comment by sam-github** [comment]
And yes, you will need to PR if you would like it fixed.

**Comment by troglobit** [comment]
Thanks for the quick reply! :)

I'll prepare a PR for 3. from a usability perspective it seems like the obvious choice.

**Comment by troglobit** [comment]
There, just posted pull request #70.  Thanks again for responding so swiftly!

**Comment by sam-github** [comment]
closed by #70
