### ISSUE TITLE
Make install is failing on man3 

### ISSUE THREAD

**Issue by dohnuts** [sam-github/libnet#82]
```
Making install in man3
 ../../.././install-sh -c -d '/home/dohnuts/fake/share/man/man3'
 /usr/bin/install -c -m 644 ././libnet*.3 '/home/dohnuts/fake/share/man/man3'
*** Error 1 in doc/man/man3 (Makefile:354 'install-man3': @list1='./libnet*.3';  list2='';  test -n "/home/dohnuts/fake/share/man/man3"  && ...)
```

this  `././libnet*.3`  is odd

**Comment by sgeto** [comment]
It's failing with what error?
The file config.log in libnet's source tree may help you debug this. Keep in mind though that this particular part of our build script is kind of a mess right now. Fancy setups and so-called out-of-source build will most like fail. I'm addressing some of these issues in PR #65 
Feel free to upload your config.log if you can't solve this one yourself.

**Comment by dohnuts** [comment]
sorry i did not copy the error.
There s nothing odd in the config.log.

out-of-source works fine, , just this to solve and it will be packaged ( for me )

**Comment by sgeto** [comment]
The error you're facing is probably the result of an out-of-source build failing. The term is not limited to just building but also includes, installation, uninstallation and packaging.
We use absolute and relative paths in our build script which isn't a good approach. It's better to use the variables source-dir, top-source-dir, doc-dir(??) ect.
Refer to the auto tools manual for more on that. Again, you can find some ideas on how to fix this and a few other issue you may be facing when building/packaging in my PR.

**Comment by dohnuts** [comment]
I can see those echo in the makefile :D 
is not `V=1 make` working

**Comment by dohnuts** [comment]
my fault, maybe make doc was not done
